#!/usr/bin/env bash
#SBATCH --mem=150GB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8  

cd /mnt/c/Users/francois.ateba/Music/
# for chnum in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22; do
for chnum in 01; do
# read in
plink2 --bgen /mnt/z/ESZEKELY/Francois_Ateba/PGS/PRS_Computation/Bristol/filtered_$chnum.bgen ref-last --sample /mnt/z/ESZEKELY/Francois_Ateba/PGS/PRS_Computation/Bristol/swapped.sample --make-bed --out chr$chnum
# remove multi allelic snps
plink19 --bfile chr$chnum --bmerge chr$chnum  --merge-mode 6
plink19 --bfile chr$chnum --exclude plink.missnp --make-bed --out chr$chnum
rm *~
rm plink.missnp
# remove duplicates
plink19 --bfile chr$chnum --list-duplicate-vars
plink19 --bfile chr$chnum --exclude plink.dupvar --make-bed --out chr$chnum
rm *~
rm plink.dupvar
# MAF
plink19 --bfile chr$chnum --freq
plink19 --bfile chr$chnum --maf 0.01 --make-bed --out chr$chnum
rm *~
rm plink.frq
done



for chnum in 01; do
# HWE
plink19 --bfile chr$chnum --hardy
plink19 --bfile chr$chnum --hwe 1e-6 --make-bed --out chr$chnum
rm *~
rm plink.hwe
# SNP missingness
plink19 --bfile chr$chnum --missing
plink19 --bfile chr$chnum --geno 0.01 --make-bed --out chr$chnum
rm *~
rm plink.imiss
# indels
awk '{ if (length($5) > 1 || length($6) > 1) print $2 }' chr$chnum.bim > indels_to_remove.txt
plink19 --bfile chr$chnum --exclude indels_to_remove.txt --make-bed --out chr$chnum
rm *~
rm indels_to_remove.txt
# add chromsome number
awk -v chnum="$chnum" 'BEGIN{OFS="\t"} {$1=chnum; print}' "chr${chnum}.bim" > "temp${chnum}.bim"
mv "temp${chnum}.bim" "chr${chnum}.bim"
done
